### ISSUE TITLE
Documentation needs to be updated for loaders (overlap and chunksize) as causing undefined errors when migrating

### ISSUE THREAD

**Issue by converseKarl** [llm-tools/embedJs#100]
It's not illustrated and is causing issues when migrating versions.

Notice also your parameters are in order of filepath+file , and specify chunk size and overlap in the right order with example

**Comment by adhityan** [comment]
Sorry about the delayed response. The library has been extensively refactored and docs updated. Could you reopen the issue if it is an issue in the `0.1.x` series?
