### ISSUE TITLE
Dependency issue when attempting to use vectordb (LanceDB)

### ISSUE THREAD

**Issue by lucastimmons** [llm-tools/embedJs#101]
After running `npm i @llm-tools/embedjs` and then trying to run `npm install vectordb` I get this error:

> code ERESOLVE
> ERESOLVE could not resolve
> 
> While resolving: @llm-tools/embedjs@0.0.94
> Found: vectordb@0.9.0
> node_modules/vectordb
>   vectordb@"*" from the root project
> 
> Could not resolve dependency:
> peerOptional vectordb@"^0.8.0" from @llm-tools/embedjs@0.0.94
> node_modules/@llm-tools/embedjs
>   @llm-tools/embedjs@"^0.0.94" from the root project
> 
> Conflicting peer dependency: vectordb@0.8.0
> node_modules/vectordb
>   peerOptional vectordb@"^0.8.0" from @llm-tools/embedjs@0.0.94
>   node_modules/@llm-tools/embedjs
>     @llm-tools/embedjs@"^0.0.94" from the root project
> 
> Fix the upstream dependency conflict, or retry
> this command with --force or --legacy-peer-deps
> to accept an incorrect (and potentially broken) dependency resolution.

**Comment by adhityan-kv-shift** [comment]
The library (on version `0.0.94`) required `vectordb` version `0.0.8` and you are installing `vectordb` version `0.0.9` and hence the error. The new version of the library `0.0.95` requires and works with `vectordb` version `0.0.9`.

So you have two options -
1. Use library version `0.0.94` with `vectordb` version `0.0.8`
2. Use library version `0.0.95` with `vectordb` version `0.0.9`
