### ISSUE TITLE
`vectordb` is deprecated in favor of `@lancedb/lancedb`

### ISSUE THREAD

**Issue by bard** [llm-tools/embedJs#107]
> The `vectordb` package is a legacy package that is  deprecated in favor of `@lancedb/lancedb`.  The `vectordb` package will continue to receive bug fixes and security updates until September 2024.  We recommend all new projects use `@lancedb/lancedb`.  See the [migration guide]migoration.md for more information.

Source: https://github.com/lancedb/lancedb/blob/51966a84f582476566daf289589318e9cc2cd0a1/docs/src/guides/tables.md?plain=1#L863

**Comment by adhityan** [comment]
Addressed in the next version.

**Comment by muditgoel01** [comment]
Cannot find package 'vectordb' imported from node_modules/@llm-tools/embedjs/dist/vectorDb/lance-db.js

**Comment by adhityan** [comment]
@muditgoel01 could you create a new issue for this. The project now uses lance-db instead of vectordb package.
