### ISSUE TITLE
OpenAI or Azure OpenAI API key or Token Provider not found, im not using it

### ISSUE THREAD

**Issue by CarmineXmX** [llm-tools/embedJs#108]
i'm starting with examples/ollama and after install and run npm start -- llama3, this error occur.

**Comment by adhityan** [comment]
Could you post the error you see?

**Comment by CarmineXmX** [comment]
Error OpenAI or Azure OpenAI API key or Token Provider not found

Il sab 7 set 2024, 05:29 Adhityan K V ***@***.***> ha scritto:

**Comment by adhityan** [comment]
This probably happens because for a vector app you need both a LLM and Embedding Model. By default, the OpenAI Large embedding models are used. This does not change if you use Ollama to power the LLM. Since it needs the OpenAI keys for the embedding model - you saw the error.
