### ISSUE TITLE
Cohere example - OpenAI or Azure OpenAI API key not found

### ISSUE THREAD

**Issue by sabatale** [llm-tools/embedJs#12]
Probably not the best issue, but..!

We are simply testing the Cohere example on Windows, but it throws `Error: OpenAI or Azure OpenAI API key not found`.

Now, this looked like Cohere would do the embeddings, etc. - so is OpenAI really needed?

Just to make sure, since there is no .env.example, this is all set through global variables, right?

In other words:

`set COHERE_API_KEY=abc`

**Comment by adhityan** [comment]
There was a bug around the default embedding being OpenAI3Small - loading of which was attempted regardless of picking a different embedding model. I have addressed this issue in a new version published today (version 0.66)

Have also updated the examples with a 'example.env' file. Let me know if it works for you. All tests are done on Linux and Mac but it should work on Windows as well.

**Comment by adhityan** [comment]
Will close this thread if there are no updates.
