### ISSUE TITLE
Add support for  libsql

### ISSUE THREAD

**Issue by HeyVincentLee** [llm-tools/embedJs#128]
libsql supports local development. It also supports AI & Embeddings. ，Vector Similarity Search is built into Turso and libSQL Server. It can serve as a local vector database for RAG.

Related Documents:

https://docs.turso.tech/features/ai-and-embeddings
https://docs.turso.tech/local-development

**Comment by adhityan** [comment]
LibSQL support is available now. Useful links - 

https://llm-tools.mintlify.app/components/vector-databases/libsql
https://github.com/llm-tools/embedJs/blob/main/examples/libsql/src/main.ts
