### ISSUE TITLE
DOC: Vector Databases > Pinecone error for import

### ISSUE THREAD

**Issue by leVoT8** [llm-tools/embedJs#136]
### Issue with current documentation:

In the documentation under vector databases for Pinecone, there may be an error unless I am missing something. 

When importing embedjs-pinecone the example shows: 
```import { LanceDb } from '@llm-tools/embedjs-pinecone';```

However, later the example calls upon `new PineconeDb` within `.setVectorDb` as shown (instead of `LanceDb`):

```
const app = await new RAGApplicationBuilder()
.setEmbeddingModel(new OpenAiEmbeddings())
.setModel(SIMPLE_MODELS.OPENAI_GPT4_O)
.setVectorDb(new PineconeDb({
...
```

This caused an error, which seems to have been resolved when I exchanged `{ LanceDb }` with `{ PineconeDb }` in the `import` statement.

**Comment by adhityan** [comment]
Thanks for pointing it out. It's addressed now.
