### ISSUE TITLE
Implement system prompt

### ISSUE THREAD

**Issue by leVoT8** [llm-tools/embedJs#144]
### 🚀 The feature

It would be great to to see EmbedJS have the ability to not only query via a user prompt but also implement a system prompt. 

### Motivation, pitch

I am seeking to create a custom GPT with RAG. It appears EmbedJS only offers a user prompt to be implemented, and not a system prompt. I would love the ability to be able to implement a system prompt as well.

**Comment by adhityan** [comment]
Actually EmbedJs already uses system prompts and this can be configured. Check out my reply on this discussion for more details on how to do it https://github.com/llm-tools/embedJs/discussions/141.

You can read more about this against the method `setQueryTemplate` in the API Reference https://llm-tools.mintlify.app/api-reference/overview

**Comment by leVoT8** [comment]
Thank you!
