### ISSUE TITLE
Conflicting dependencies with Vector DBs

### ISSUE THREAD

**Issue by GullyTechIO** [llm-tools/embedJs#15]
I had a big long Discussion post outlining all of the steps I took and all the things that went wrong while trying to see "how easy it is to get started", particularly in regards to the incomplete documentation not saying anything about node.js needing

```
const { RAGApplicationBuilder, WebLoader, YoutubeLoader, SitemapLoader, SIMPLE_MODELS} = require('@llm-tools/embedjs');
const path = require('path');
```

Which is _kind of important_.

But while trying to figure it all out, discovered that the effort was fruitless anyway because different modules of the main project have conflicting dependencies.

Trying to install LanceDB:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @langchain/community@0.0.35
npm WARN Found: vectordb@0.4.16
npm WARN node_modules/vectordb
npm WARN   vectordb@"*" from the root project
npm WARN   1 more (@llm-tools/embedjs)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional vectordb@"^0.1.4" from @langchain/community@0.0.35
npm WARN node_modules/@langchain/community
npm WARN   @langchain/community@"^0.0.35" from @llm-tools/embedjs@0.0.66
npm WARN   node_modules/@llm-tools/embedjs
npm WARN
npm WARN Conflicting peer dependency: vectordb@0.1.19
npm WARN node_modules/vectordb
npm WARN   peerOptional vectordb@"^0.1.4" from @langchain/community@0.0.35
npm WARN   node_modules/@langchain/community
npm WARN     @langchain/community@"^0.0.35" from @llm-tools/embedjs@0.0.66
npm WARN     node_modules/@llm-tools/embedjs
```

"@langchain/community" requires vectordb version 0.1.4
"@llm-tools/embedjs" requires vectordb version 0.1.19

So I scrapped it, started again and tried hnswlib-node

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @langchain/community@0.0.35
npm WARN Found: hnswlib-node@3.0.0
npm WARN node_modules/hnswlib-node
npm WARN   hnswlib-node@"*" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional hnswlib-node@"^1.4.2" from @langchain/community@0.0.35
npm WARN node_modules/@langchain/community
npm WARN   @langchain/community@"^0.0.35" from @llm-tools/embedjs@0.0.66
npm WARN   node_modules/@llm-tools/embedjs
npm WARN
npm WARN Conflicting peer dependency: hnswlib-node@1.4.2
npm WARN node_modules/hnswlib-node
npm WARN   peerOptional hnswlib-node@"^1.4.2" from @langchain/community@0.0.35
npm WARN   node_modules/@langchain/community
npm WARN     @langchain/community@"^0.0.35" from @llm-tools/embedjs@0.0.66
npm WARN     node_modules/@llm-tools/embedjs
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @llm-tools/embedjs@0.0.66
npm ERR! Found: hnswlib-node@3.0.0
npm ERR! node_modules/hnswlib-node
npm ERR!   hnswlib-node@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional hnswlib-node@"^2.1.1" from @llm-tools/embedjs@0.0.66
npm ERR! node_modules/@llm-tools/embedjs
npm ERR!   @llm-tools/embedjs@"^0.0.66" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: hnswlib-node@2.1.1
npm ERR! node_modules/hnswlib-node
npm ERR!   peerOptional hnswlib-node@"^2.1.1" from @llm-tools/embedjs@0.0.66
npm ERR!   node_modules/@llm-tools/embedjs
npm ERR!     @llm-tools/embedjs@"^0.0.66" from the root project
```

"@langchain/community" is compatible with hnswlib-node 1.4.2
"@llm-tools/embedjs" is compatible with hnswlib-node 2.1.1

Pinecone installed.. but I really don't want to have to make another account on another site.

**Comment by adhityan** [comment]
Hello @GullyTechIO thanks for creating an issue. It's unclear what conflicting dependencies you see. The LanceDB is not an error - jsut a warning. I have tried to make sure the library uses the latest versions of the libraries (while some other internal dependencies may reference older versions). This means you might see this warning in verbose install but this is not going to be an issue for any users. The library has clear `overrides` specified in its `package.json` for this.

For HNSW-DB, the version originally supported by the library was 2.1.1 and you were trying to install the latest version 3.0.0. hnswlib-node 3.0.0 was released last month and support for this was not yet added. That is the error you see. I tested it today with version 2.1.1 and saw no error.

If you want to help, it's easy to send in a PR to add support for a newer version of a library if you need it. Your account was created just a few hours ago, so I am not sure if you have history with open source, but it's usually easy to contribute to it and that's how we all benefit.

Regardless, I have published a new version of EmbedJs with support for hnswlib-node 3.0.0. This should work out of the box for you. Hopefully, that addresses your problem.
