### ISSUE TITLE
Documentation: Missing Object

### ISSUE THREAD

**Issue by leVoT8** [llm-tools/embedJs#155]
### 🚀 The feature

In `Components > Vector Databases` 

Missing: `import { WebLoader } from '@llm-tools/embedjs-loader-web';` for all of the examples. 

### Motivation, pitch

Reviewing the documentation and noticed that WebLoader is not imported and called upon in the code example.

**Comment by adhityan** [comment]
Thanks for pointing it out. Will be addressed in the next release.
