### ISSUE TITLE
Adding Excel as a loader

### ISSUE THREAD

**Issue by converseKarl** [llm-tools/embedJs#16]
I want to be able to add excel as a load, or upload it and answer questions from a reasonable structureds spreadsheet with product info, description column and pricing.

Is that possible? can this common pattern be added?

Great libary, and do you have a paypal or funding link for a coffee fund! Happy to buy a round of coffee's

**Comment by adhityan** [comment]
The library does not support excel currently. I want to add it but I am not sure what is the right strategy to embed excel files. I will research this and send in a PR.

**Comment by adhityan** [comment]
No paypal or funding link! In my day job, my teams work a lot on ML and GenAI. I created this to just give back to the community. 

But I appreciate the sentiment :)

**Comment by adhityan** [comment]
Added experimental support for excel loader in version `0.0.73`. Will test this out more and then close the issue soon.

**Comment by adhityan** [comment]
Tested
