### ISSUE TITLE
local path loader issue

### ISSUE THREAD

**Issue by RaghvindYadav** [llm-tools/embedJs#160]
I tried the following code.

>      const ragApplication = await new RAGApplicationBuilder()
>             .setModel(new Ollama({ modelName: llamaVersion, baseUrl: llamaHostUrl }))
>             .setEmbeddingModel(new OllamaEmbeddings({ model: 'nomic-embed-text', baseUrl: llamaHostUrl }))
>             .setVectorDatabase(new HNSWDb())
>             .build();
> 
>         ragApplication.addLoader(new UrlLoader({url: "https://www.forbes.com/profile/elon-musk"}));
>       
>         const ragResponse = await ragApplication.query('What is the net worth of Elon Musk today?');
>      
>         console.log('response: ',ragResponse);

output:

```
response:  {
  id: '6b8b201d-a839-470e-b675-5603891934e8',
  timestamp: 2024-11-07T13:10:45.224Z,
  content: "I don't have the most up-to-date information on Elon Musk's current net worth. My knowledge cutoff is December 2023, and I may not have reflected any recent changes in his wealth. For the most accurate and current information, I recommend checking reputable financial news sources or Elon Musk's official social media accounts.",
  actor: 'AI',
  sources: [],
  tokenUse: { inputTokens: 'UNKNOWN', outputTokens: 'UNKNOWN' }
}
```

Not working with any url for me. Help me to fix this.

**Comment by adhityan** [comment]
Could you run the app with debug logs enabled? This will let you know why the loader did not pick up the url. 

You can enable debug logs by setting the environment variable DEBUB like so -

`DEBUG=embedjs:*`
