### ISSUE TITLE
Error: Anthropic API key not found

### ISSUE THREAD

**Issue by tes735** [llm-tools/embedJs#164]
### 🐛 Describe the bug

Implementing this into an electron app. I got the openai and ollama parts to work. Now, I'm trying to get the Anthropic implementation to work. I'm getting this: Error: Anthropic API key not found. I created a key at Anthropic and added credits. The implementation looks correct and as I said, the other two work. Any thoughts on how I can troubleshoot this, or is it a bug?

**Comment by adhityan** [comment]
Hey @tes735 sorry for the delayed response. I tested with Anthopic models and they seem to be working fine. If you were unable to fix the error, could you share more info on exactly how you configured the application along with the debug logs?

**Comment by tes735** [comment]
I'm not in front of that computer at the moment, but I set it up similarly to how openAI is set up. I didn't see anything specific about how to get it to work with RAGApplicationBuilder. Do you have a good example somewhere that I can check out? Thanks for the reply!

**Comment by adhityan** [comment]
It should be straightforward. Here are the three things to be done - https://llm-tools.mintlify.app/components/llms/anthropic

Could you share the exact error message you see - the full trace?

**Comment by JotaOdiceu** [comment]
Guys, I went through this, installed dotenv and put the import "dotenv" at the beginning of my file, that solved it for me

**Comment by adhityan** [comment]
Yay
