### ISSUE TITLE
Qdrant Vector Database support

### ISSUE THREAD

**Issue by adek** [llm-tools/embedJs#18]
It would be great if you could add Qdrant vector database to your project.

**Comment by adhityan** [comment]
Hello, the library does support Qdrant already, I seem to have missed updating the documentation - will fix this. In the meantime, you cann use Qdrant by doing the following -

1. Install qdrant support package `@qdrant/js-client-rest`
2. Import QdrantDb from `@llm-tools/embedjs/vectorDb/qdrant`
3. Set vectorDB to QdrantDb like so `.setVectorDb(new QdrantDb({ apiKey: string; url: string; clusterName: string }))`

**Comment by adhityan** [comment]
Added to documentation
