### ISSUE TITLE
LanceDb not defined

### ISSUE THREAD

**Issue by converseKarl** [llm-tools/embedJs#19]
I know all my libraries are installed, as they imported, other libraries are loading but lanceDb won't instantiate. DB folder exists relative to the script running.

I get ReferenceError: LanceDb is not defined

**import {RAGApplicationBuilder, PdfLoader, YoutubeSearchLoader, SitemapLoader, WebLoader, TextLoader } from '@llm-tools/embedjs';**

async function setupRagApplication() {
    try {
        const ragApplication = await new RAGApplicationBuilder()
            .addLoader(new YoutubeSearchLoader({ searchString: 'Tesla cars' }))
            .addLoader(new SitemapLoader({ url: 'https://tesla-info.com/sitemap.xml' }))
            .addLoader(new WebLoader({ url: 'https://en.wikipedia.org/wiki/Tesla,_Inc.' }))
            **.setVectorDb(new LanceDb ({ path: path.resolve('/db') })) // Ensure path is correct**
            .build();
              console.log('RAG application built successfully:', ragApplication);
    } catch (error) {
              console.error('Failed to build RAG application:', error);
    }
}

setupRagApplication();

**Comment by adhityan** [comment]
Have you installed the dependency for LanceDB?

`npm install vectordb`

Once done, you need to import LanceDB from '@llm-tools/embedjs/vectorDb/lance'

**Comment by converseKarl** [comment]
that's now resolved, wasn't in the docs, so could not understand the import structure. It's now going off to website and building the lance db in the folder relative to script as its building and not failing.  However querying is failing what imports do i need to specify for this

.ragApplication.query('Tell me about the history of Tesla?')
Failed to build RAG application: TypeError: Cannot read properties of undefined (reading 'query')

Notice youtube issue's a fetch warning "experimental". I'm using node v18, moving to v20 soon.

**Comment by adhityan** [comment]
Fair point on the docs. Will update it to include the import paths.
