### ISSUE TITLE
Ability to specify text size splitter and overlap block size for loaders

### ISSUE THREAD

**Issue by converseKarl** [llm-tools/embedJs#27]
Be able to set the text split size for the text splitter server

**Comment by adhityan** [comment]
Hey @converseKarl, thanks for pointing out this could be useful. I am in the middle of adding support for Docx files and a few other topics. Would you be interested in sending in a PR for this? Otherwise I will get to it after the current set of tasks.

**Comment by adhityan** [comment]
Added support for this in version `0.0.74`. Two optional parameters (`chunkSize` and `chunkOverlap`) exist in all loaders to configure this.
