### ISSUE TITLE
Open-3Large-Embeddings has constructor pointing to small model

### ISSUE THREAD

**Issue by converseKarl** [llm-tools/embedJs#36]
**this must be a bug?**
export class OpenAi3LargeEmbeddings implements BaseEmbeddings {
    private model: OpenAIEmbeddings;

    constructor() {
        this.model = new OpenAIEmbeddings({ modelName: **'text-embedding-3-small',** maxConcurrency: 3, maxRetries: 5 });
    }

also how do you import these models via import statement?

**Comment by adhityan** [comment]
Yes, this is a bug. Will address this in the next release/

**Comment by adhityan** [comment]
Addressed in version `0.0.68`
