### ISSUE TITLE
Add dynamic dimensions capability to GPT Embeddings models

### ISSUE THREAD

**Issue by converseKarl** [llm-tools/embedJs#40]
Apparently this can optimize the cost, performance whilst still out performing ada and small gpt models. Adding this will bake in flexibility for future.

See note below

https://platform.openai.com/docs/guides/embeddings/use-cases

**Comment by adhityan** [comment]
Not all embedding models support dynamic dimensions. I have added it to the `OpenAi3LargeEmbeddings` model. Simply set the optional parameter `dynamicDimension` in the constructor. We can also add it to any other embedding model that supports this.

Will be available in the next version published.

**Comment by adhityan** [comment]
Included in version `0.0.73`
