### ISSUE TITLE
add optional query format response JSON rather than just text response

### ISSUE THREAD

**Issue by converseKarl** [llm-tools/embedJs#43]
I believe in openai you can now do this?

{ "type": "json_object" 

as part of the query, i think it would be sensible to have text and non-text options. So

.setFormat('json')

**Comment by adhityan** [comment]
is this useful ? This can also be achieved for most models by prompt engineering as well. There is a slim benefit to supporting the more native json format in just OpenAi. It complicates the API for all models.

**Comment by adhityan** [comment]
Closing this for now. We can revisit this if there are usecases which are blocked by this. In the meantime, one can always get a JSON response by adding that to the prompt.
