### ISSUE TITLE
Support for VertexAI for Gemini LLM and Embedding

### ISSUE THREAD

**Issue by tsibg** [llm-tools/embedJs#46]
I am interested in support for Gemini models, preferably on VertexAI by Google Cloud Platform. 
The Gemini 1.5 Pro supports up to 1M Context, which could open a bunch of possibilities for grounding and RAG. Further more it is multimodal (text, images, audio, PDFs, code, videos). 

**Resources for the integration:**

LLM and Embedding models on VertexAI:
- https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models

Langchain LLM support for VertexAI and all Gemini models:
- https://js.langchain.com/docs/integrations/llms/google_vertex_ai

Langchain Embeddings on VertexAI (Expirimental):
_Supports both `textembedding-gecko` and `multimodalembedding@001`_
- https://js.langchain.com/docs/modules/data_connection/experimental/multimodal_embeddings/google_vertex_ai
 
I'm currently working on the integration, it looks pretty straight forward. 
Will also submit a PR, if the authors are interested.
 
P.S. Thanks for creating this library, well structured and easy to use.

**Comment by adhityan** [comment]
Thank you @tsibg both for engaging and also for the PR. Let's get it merged in.

**Comment by adhityan** [comment]
Published new version `0.0.72` with merged changes. 

I like the idea of natively supporting multimodal. RAG is still useful in a multimodal setup. I will start a discussion thread on the best way to go ahead with support for this in the library.
