### ISSUE TITLE
PINECONE_ENVIRONMENT is deprecated

### ISSUE THREAD

**Issue by vgkids** [llm-tools/embedJs#5]
When signing up for a new Pinecone account, a value for `PINECONE_ENVIRONMENT` is no longer provided:
https://github.com/pinecone-io/pinecone-ts-client/blob/main/v2-migration.md

Moving to version 2.0.1 of @pinecone-database/pinecone allows you to use the new keys provided, with a few minor changes to pinecone-db.ts.

**Comment by adhityan** [comment]
I have addressed this. You can now provide an `indexSpec` parameter to the PineconeDb constructor that specifies the details of the new index. The environment variable `PINECONE_ENVIRONMENT` is not required.
