### ISSUE TITLE
Removing Rag Items does not update the Rag Loaders after moveing the embedding

### ISSUE THREAD

**Issue by converseKarl** [llm-tools/embedJs#59]
What is the right procedure to remove the  item from the loader (or all items)

I can remove the embedding using deleteEmbeddingsFromLoader  and this works but the loader reference from a previous add is still hanging around and present in the loaders list

        **await ragApplication.deleteEmbeddingsFromLoader(uniqueLoaderId, true); /* works */**

        **ragApplicationBuilder.deleteLoader(uniqueLoaderId);  /* ? something like this to follow on? */**

**Comment by adhityan** [comment]
Do you mean just the reference is still present in the internal `loaders` list? I think it's best to jst have a `deleteLoader` method - I don't see any reason to have both.

**Comment by adhityan** [comment]
Made changes around this. Take a look and re-open the issue if it does not address your point.

**Comment by converseKarl** [comment]
OK so we should be using?

       ragApplication.deleteLoader(uniqueLoaderId, true);
