### ISSUE TITLE
Timeout Error, Fetch failed in NodeJS

### ISSUE THREAD

**Issue by Ilikepizza2** [llm-tools/embedJs#60]
No matter which managed vectorDB I try to use, I get timeout error - fetch failed. I've tried pinecone, qdrant. I get this error(for pinecone) - 
`error PineconeConnectionError: Request failed to reach Pinecone. This can occur for reasons such as network problems that prevent the request from being completed, or a Pinecone API outage. Check your network connection, and visit https://status.pinecone.io/ to see whether any outages are ongoing.`

Is there something I need to look out for while using the client for nodejs?

**Comment by adhityan** [comment]
I just tested it with Pinecone and everthingt seems to be working fine. Are you sure there are no firewalls in between your machine and these servers? Best way to check that is ping / access the APIs using Postman I suppose.

**Comment by Ilikepizza2** [comment]
Yup I've tried it with the python client as well as curl method too. Don't know what to do.

**Comment by adhityan** [comment]
Intresting. Thanks for letting me know. If you don't mind, why do you like Pinecone? There are so many vector databases out there these days - both new players as well as existing vendors adding vector support; it's become difficult to make the right choices.

**Comment by Ilikepizza2** [comment]
I've tried a lot of them. I liked chroma/pgvector most tbh. As for now, I just wanted to get a prototype project up asap. Pinecone was the most suitable for my needs (cloud, managed and a good free tier). That's why I'm using embedJS too XD
