### ISSUE TITLE
Chroma in NPM

### ISSUE THREAD

**Issue by alphiecore** [llm-tools/embedJs#64]
it appears that ChromaDB is not exported within the NPM Module.  also, think Ollama embeddings is missing unless i'm doing something wrong?

Module '"@llm-tools/embedjs"' has no exported member 'ChromaDb'.ts(2305)

**Comment by adhityan** [comment]
You will need to import ChromaDB like so `import { ChromaDb } from '@llm-tools/embedjs/vectorDb/chroma';

Please refer to the [Chroma related documentation](https://github.com/llm-tools/embedJs?tab=readme-ov-file#chroma) for more information.
`
Regarding Ollama, the library currently only supports using LLMs via Ollama; support for Ollama embeddings is coming soon but not available yet.
