### ISSUE TITLE
Multi AI Agent Support

### ISSUE THREAD

**Issue by DavideCarvalho** [llm-tools/embedJs#65]
Hey guys, great job with embedJS. IMO it's the easiest way of adding LLM into a nodejs project right now, you guys are doing a great job!

I don't know if you guys have seen it, but one of the latest things AI community is talking is about Multi AI Agents. I think this would take embedJS to another level, since there aren't many nodejs libraries that does that

https://www.youtube.com/watch?v=sal78ACtGTc here's a talk about Multi AI Agents

I've found one NodeJS library that supports it: https://github.com/metaskills/experts

**Comment by adhityan** [comment]
Thank you for your kind words. We are working to make it even more easier to use this linrary with the upcomming PR - https://github.com/llm-tools/embedJs/pull/66, which adds support for inferring the data being added dynamically. It can auto import entire directories with a single line.

I am certainly keeping an eye on Multi AI agents. The current idea is to add support for this as a separate package; one that is fully compatible with this library. Timeline, will keep this updated. All I can say for now is, this will be something we will for sure explore in the upcoming months.
