### ISSUE TITLE
Allow conversation history to persist

### ISSUE THREAD

**Issue by davetaz** [llm-tools/embedJs#79]
One of the layers that is not yet abstracted is conversation history, this is currently managed in memory and lost between sessions. 

Abstracting this, similar to cache, would allow the history to persist between sessions. The implementation could also add things like timestamp and sources to messages so these can also be reloaded. 

Happy to open the pull request with this in as I do have it implemented with in-memory (legacy) and mongoDb support. 

Explore this at https://github.com/llm-tools/embedJs/compare/main...SAGE-RAI:embedJs:main

**Comment by adhityan** [comment]
Thanks, this makes a lot of sense; let's add this in as the last feature to be merged in before the move to a monorepo. I will review the diff and follow up.

**Comment by converseKarl** [comment]
At moment I am storing conversation histories using NodeCache, its not DB or permanent but it's good enough for most cases i.e. time to live (so can keep them there for a good hour or day without any problems if you have reasonable diskspace. I feed the previous history in and or summarize it rotating it with set and get on a session.  It works well with the rag, and provides limited historical context overlay.  Just putting some shared experience out there.

**Comment by adhityan** [comment]
I have merged the nice PR from @davetaz. There were a few changes I made to the code but overall functionality remains the same. It is available in the version `0.0.91`.

**Comment by davetaz** [comment]
Thanks so much for this. It is much appreciated and we look forward to help you continue the work to improve this valuable library for everyone.

**Comment by adhityan** [comment]
Thank you too. This is the spirit of open source.
