### ISSUE TITLE
Support for Amazon Titan

### ISSUE THREAD

**Issue by azhar-zuberi** [llm-tools/embedJs#8]
Are there / can there be any plans to support Amazon Titan in the near future?

**Comment by adhityan** [comment]
I would certainly like to add support for Amazon Titan at some point. But its not planned for the near future. Right now, most of my focus is taken in adding support for Azure services - as we use Azure extensively internally. 

What you could do -
> Try writing a new EmbeddingModel / BaseModel class to add support for Amazon Titan and send in a PR. I can on priority - clean up, add documentation and merge it if you send in a PR.

Let me know you can do that.

**Comment by adhityan** [comment]
Closing this issue for now. Please feel free to open a thread in the Discussions panel if you would like to discuss more.
