### ISSUE TITLE
Add OllamaEmbedding (It is available in langchain)

### ISSUE THREAD

**Issue by hassanallaham** [llm-tools/embedJs#84]
Most people (companies) prefer to keep their data local and avoid sharing it with embedding model providers. In fact, no one likes to be exposed :cactus:  :smile:  😋

**Comment by adhityan** [comment]
This is part of the current roadmap. Should be added in the next few releases.

**Comment by adhityan** [comment]
Early support added in version `0.0.92`. More testing pending.
