### ISSUE TITLE
Windows install problem version 0.0.89

### ISSUE THREAD

**Issue by fdx-matias** [llm-tools/embedJs#85]
I tried to install version 0.0.89 Windows environment and i got this error :

 gyp ERR! build error
│ gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onExit (C:\Users\Mati\AppData\Local\node\corepack\pnpm\8.5.1\dist\node_modules\node-gyp\lib\build.js:203:23)
│ gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
│ gyp ERR! System Windows_NT 10.0.22621
│ gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mati\\AppData\\Local\\node\\corepack\\pnpm\\8.5.1\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
│ gyp ERR! cwd C:\Findex\Repositories\x-flow\node_modules\.pnpm\mmmagic-patched@0.5.5\node_modules\mmmagic-patched
│ gyp ERR! node -v v18.16.1
│ gyp ERR! node-gyp -v v9.3.1
│ gyp ERR! not ok

It's related to mmmagic-patched@0.5.5 lib. I installed 0.0.88 and i didn't have any problem!

**Comment by adhityan** [comment]
Have published a new version replacing the dependency that was breaking all windows installs. Could you check with version `0.0.90` and let me know if your issue is resolved?

**Comment by adhityan** [comment]
Closing this issue as the fix is expected to work. Please reopen / create a new issue if required.
