### ISSUE TITLE
 throw new Error("OpenAI or Azure OpenAI API key or Token Provider not found");

### ISSUE THREAD

**Issue by MB2** [llm-tools/embedJs#96]
I set the RAG application with Ollama (vector db LanceDB) but keep getting this error. What can I do?
Here's my code:

`const ragApplication = await new RAGApplicationBuilder()
    .setModel(new Ollama({
        modelName: "llama3",
        baseUrl: 'http://localhost:11434'
        }))
    .addLoader({ type: 'YoutubeSearch', youtubeSearchString: 'Tesla cars' })
    .addLoader('https://en.wikipedia.org/wiki/Tesla,_Inc.')
    .addLoader('https://tesla-info.com/sitemap.xml')
    .setVectorDb(new LanceDb({ path: '.db' }))
    .build();`

**Comment by ashok-ayyarchamy** [comment]
Same here, By default langchain picks openAI embeddings model. I tried to change the embeddings model as well but no good

**Comment by adhityan** [comment]
Closing issue - this is not a bug.
