### ISSUE TITLE
Revisit - Embeddings Tokens In, Out, Total and Cost - Critical for hosting and using this library

### ISSUE THREAD

**Issue by converseKarl** [llm-tools/embedJs#98]
I'm seeing this on Langchain in the API, and we definitely need this information

Query results should return the tokens in, out and total and if possible cost but this could be done aside by the developer if necessary using the in/out tokens applying the model cost

People are telling me out there, if the tokens cannot be quantified for cost any libraries are just a non-starter.

Thanks so much for your amazing work, your doing a fantastic job!

**Comment by adhityan** [comment]
I have published a new version today that includes this information. Now the query method will return an additional parameter `tokenUse`. This is the type -

```TS
tokenUse: {
    inputTokens: number | 'UNKNOWN';
    outputTokens: number | 'UNKNOWN';
};
```

The Unknown is sent back when the token use information is not available from the model. Hope this helps.

**Comment by converseKarl** [comment]
this is really useful. thank you!
